---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  vars:
    run_not_in_container: false
  tasks:
    - name: Run primary role
      ansible.builtin.include_role:
        name: silabeer.freeipa
